### ISSUE TITLE
Investigate multiplayer support

### ISSUE THREAD

**Issue by SuperV1234** [SuperV1234/quakevr#1]

**Comment by nephatrine** [comment]
This is the only thing stopping me from really enjoying this fyi. I don't think it would be worthwhile to have multiplayer support for non-VR servers since having to support the non-VR netcode/protocol would limit the VR functionality too much... but being able to do multiplayer/coop with other quakevr players would be the bees knees.

**Comment by SuperV1234** [comment]
I should be able to get this to work for v0.0.5. ;)

**Comment by SuperV1234** [comment]
v0.0.5 has full multiplayer support.
